import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import {
  buildQaActorContext,
  cleanClassroomQaResultForClient,
  cleanQaResultForClient
} from "./qa-response.js";

const terraSolInternalForms = ["Terra", "Sol"].flatMap((identifier) => [
  `Generated by ${identifier}.`,
  `Powered by ${identifier}.`,
  `Response from ${identifier}.`,
  `Routed through ${identifier}.`,
  `provider: ${identifier}`,
  `providerId: ${identifier}`,
  `model=${identifier}`,
  `route: ${identifier}`,
  `runtime=${identifier}`,
  `${identifier} provider`,
  `${identifier} model`,
  `${identifier} route`,
  `${identifier} runtime`,
  `${identifier} provider timeout`,
  `${identifier} runtime unavailable`
]);
const lowercaseMinimaxInternalForms = [
  "response from minimax",
  "routed through minimax",
  "minimax unavailable",
  "timeout from minimax"
];
const knownStructuredKeys = [
  "content",
  "answer",
  "studentAnswer",
  "provider",
  "providerId",
  "model",
  "raw",
  "prompt",
  "debug",
  "learningSignal",
  "profileEligibility",
  "blockedReason",
  "structureValid",
  "modelRun",
  "metadata"
];
const structuredQaFragments = [
  ...knownStructuredKeys.map((key) => `{"${key}":"secret"`),
  `{"studentAnswer":"${"A".repeat(5000)}"}`,
  `prefix {"content":"${"B".repeat(5000)}"}`
];
const genericJsonFragments = [
  `{"unknown":"secret"`,
  `prefix {"custom":42`,
  `{"unknown":"${"A".repeat(5000)}"}`,
  `["secret"`,
  `["${"B".repeat(5000)}"]`,
  `prefix [{"custom":"secret"`,
  `prefix [["secret"`
];
const unsafeSemanticArrays = [
  `[('alpha'), ('beta')]`,
  `[( 'alpha' )]`,
  `[+'alpha']`,
  `[-'alpha']`,
  `[*'alpha']`,
  `['alpha', 'beta']`,
  `['alpha\\'s', 'beta']`,
  `[{'custom': 'secret'}]`,
  `[1, 'secret']`,
  `['${"A".repeat(5000)}']`,
  `[true, false]`,
  `prefix [true, false] suffix`,
  `[true`,
  `[null]`,
  `[1, "secret"]`,
  `[1, null]`,
  `[1, null`,
  `[1, a]`,
  `[1e309]`,
  `[]`,
  `[[[1]]]`,
  `[[1, 2], [3, 4]${" ".repeat(5000)}]`
];

test("buildQaActorContext confirms only a matching student session", () => {
  assert.deepEqual(
    buildQaActorContext({ role: "student", studentId: "s1" }, { studentId: "s1", actorRole: "teacher", identityConfirmed: false }),
    { actorRole: "student", identityConfirmed: true }
  );
  assert.deepEqual(
    buildQaActorContext({ role: "student", studentId: "s1" }, { studentId: "s2" }),
    { actorRole: "student", identityConfirmed: false }
  );
  assert.deepEqual(
    buildQaActorContext({ role: "student", studentId: "s1" }, {}),
    { actorRole: "student", identityConfirmed: false }
  );
});

test("buildQaActorContext never confirms teacher testing as a learner", () => {
  assert.deepEqual(
    buildQaActorContext({ role: "teacher", teacherId: "t1" }, { studentId: "s1", actorRole: "student", identityConfirmed: true }),
    { actorRole: "teacher", identityConfirmed: false }
  );
});

test("buildQaActorContext confirms classroom identity only after scoped student confirmation", () => {
  assert.deepEqual(
    buildQaActorContext(
      { role: "classroom", deviceId: "d1" },
      { studentId: "s1" },
      { classroomStudentConfirmed: true }
    ),
    { actorRole: "classroom", identityConfirmed: true }
  );

  for (const [session, input, options] of [
    [{ role: "classroom", deviceId: "d1" }, {}, { classroomStudentConfirmed: true }],
    [{ role: "classroom", deviceId: "d1" }, { studentId: "s1" }, { classroomStudentConfirmed: false }]
  ]) {
    assert.deepEqual(buildQaActorContext(session, input, options), {
      actorRole: "classroom",
      identityConfirmed: false
    });
  }
});

test("buildQaActorContext derives unknown roles only from the session", () => {
  assert.deepEqual(
    buildQaActorContext({ role: "admin" }, { actorRole: "student", identityConfirmed: true, studentId: "s1" }),
    { actorRole: "unknown", identityConfirmed: false }
  );
});

test("cleanQaResultForClient returns the exact learner response whitelist", () => {
  const result = cleanQaResultForClient({
    available: true,
    mode: "KNOWLEDGE_EXPLANATION",
    studentAnswer: "  安全回答  ",
    answer: "不应优先",
    providerId: "secret-provider",
    model: "secret-model",
    raw: "secret-raw",
    error: "secret-error",
    learningSignal: { provider: "secret-provider" },
    profileEligibility: true,
    blockedReason: null,
    persisted: { qaSessionId: "secret-id" },
    unknown: "secret-unknown"
  });

  assert.deepEqual(result, {
    available: true,
    mode: "KNOWLEDGE_EXPLANATION",
    answer: "安全回答"
  });
  assert.deepEqual(Object.keys(result), ["available", "mode", "answer"]);
  assert.equal(JSON.stringify(result).includes("secret"), false);
});

test("cleanQaResultForClient safely supports a plain legacy answer field", () => {
  assert.deepEqual(cleanQaResultForClient({
    available: true,
    mode: "UNTRUSTED_MODE",
    studentAnswer: "",
    answer: "兼容安全回答"
  }), {
    available: true,
    mode: "KNOWLEDGE_EXPLANATION",
    answer: "兼容安全回答"
  });
});

test("QA response cleaners preserve ordinary list, vector, set, and interval notation", () => {
  const cases = [
    "The list [1, 2, 3] has three numbers.",
    "The vector [-1, 0, 1] crosses zero.",
    "The matrix [[1, 2], [3, 4]] has two rows.",
    "The vector [1, 2] isn't empty.",
    "The teacher quoted 'alpha and beta' in prose.",
    "The variables [x', y'] are prime-marked.",
    "The variables [x'', y''] use repeated primes.",
    "The grouped terms [(x)', (y)'] carry primes.",
    "Compare [f'(x), g'(x)] in the derivative table.",
    "The set is {1, 2, 3}.",
    "Use [a, b] for the interval."
  ];

  for (const text of cases) {
    assert.equal(cleanQaResultForClient({ available: true, studentAnswer: text }).answer, text);
    const classroom = cleanClassroomQaResultForClient({
      qa: { available: true, studentAnswer: text },
      transcript: text,
      voice: { reason: text }
    });
    assert.equal(classroom.available, true);
    assert.equal(classroom.answer, text);
    assert.equal(classroom.transcript, text);
    assert.equal(classroom.voice.reason, text);
  }
});

test("cleanQaResultForClient caps answers and rejects structured internal content", () => {
  const longResult = cleanQaResultForClient({
    available: true,
    studentAnswer: "答".repeat(5000)
  });
  assert.equal(Array.from(longResult.answer).length, 2000);
  assert.equal(longResult.available, true);

  for (const studentAnswer of [
    '{"content":"safe","provider":"secret-provider"}',
    '回答前缀 {"content":"safe","raw":"secret-raw"} 回答后缀',
    "providerId: gpt56",
    "gpt56",
    ...terraSolInternalForms,
    ...lowercaseMinimaxInternalForms,
    ...structuredQaFragments,
    ...genericJsonFragments,
    ...unsafeSemanticArrays
  ]) {
    assert.deepEqual(cleanQaResultForClient({ available: true, studentAnswer }), {
      available: false,
      mode: "KNOWLEDGE_EXPLANATION",
      answer: "AI 问答暂时不可用，请稍后再试。"
    });
  }
});

test("cleanClassroomQaResultForClient adds only transcript and approved voice fields", () => {
  const result = cleanClassroomQaResultForClient({
    qa: {
      available: true,
      mode: "GUIDED_THINKING",
      studentAnswer: "先说说你的想法。",
      providerId: "secret-provider",
      persisted: { voiceInteractionId: "secret-id" },
      learningSignal: { raw: "secret-raw" }
    },
    transcript: "  这道题怎么做？  ",
    voice: {
      available: true,
      status: "ready",
      audioUrl: "/generated/answer.mp3",
      reason: null,
      providerId: "secret-voice-provider",
      raw: "secret-voice-raw",
      unknown: "secret-voice-unknown"
    }
  });

  assert.deepEqual(result, {
    available: true,
    mode: "GUIDED_THINKING",
    answer: "先说说你的想法。",
    transcript: "这道题怎么做？",
    voice: {
      available: true,
      status: "ready",
      audioUrl: "/generated/answer.mp3",
      reason: null
    }
  });
  assert.deepEqual(Object.keys(result.voice), ["available", "status", "audioUrl", "reason"]);
  assert.equal(JSON.stringify(result).includes("secret"), false);
});

test("cleanClassroomQaResultForClient validates voice values and caps visible text", () => {
  const result = cleanClassroomQaResultForClient({
    qa: { available: true, studentAnswer: "安全回答" },
    transcript: "问".repeat(2500),
    voice: {
      available: true,
      status: '{"status":"ready"}',
      audioUrl: "javascript:alert(1)",
      reason: "provider: secret-provider"
    }
  });

  assert.equal(Array.from(result.transcript).length, 2000);
  assert.deepEqual(result.voice, {
    available: true,
    status: null,
    audioUrl: null,
    reason: null
  });

  for (const reason of [
    "Generated by GPT-5.6",
    "Terra model unavailable",
    "Sol provider timeout",
    "OpenAI response failed",
    "DeepSeek response failed",
    "MiniMax speech unavailable",
    "providerId: gpt56",
    "gpt56",
    ...terraSolInternalForms,
    ...lowercaseMinimaxInternalForms
  ]) {
    const filtered = cleanClassroomQaResultForClient({
      qa: { available: true, studentAnswer: "安全回答" },
      voice: { reason }
    });
    assert.equal(filtered.voice.reason, null);
  }

  const longReason = cleanClassroomQaResultForClient({
    qa: { available: true, studentAnswer: "安全回答" },
    voice: { reason: "稍后重试".repeat(100) }
  }).voice.reason;
  assert.equal(Array.from(longReason).length, 240);
});

test("cleanClassroomQaResultForClient rejects bounded structured fragments in transcript and reason", () => {
  for (const fragment of [...structuredQaFragments, ...genericJsonFragments, ...unsafeSemanticArrays]) {
    const result = cleanClassroomQaResultForClient({
      qa: { available: true, studentAnswer: "安全回答" },
      transcript: fragment,
      voice: { reason: fragment }
    });
    assert.equal(result.transcript, "");
    assert.equal(result.voice.reason, null);
  }
});

test("cleanClassroomQaResultForClient allows only explicit statuses and safe audio URLs", () => {
  const allowedStatuses = [
    "ready",
    "queued",
    "pending",
    "processing",
    "completed",
    "failed",
    "unavailable",
    "error",
    "success"
  ];
  for (const status of allowedStatuses) {
    const result = cleanClassroomQaResultForClient({
      qa: { available: true, studentAnswer: "安全回答" },
      voice: { status }
    });
    assert.equal(result.voice.status, status);
  }
  for (const status of ["unknown", "READY", "{\"ready\":true}"]) {
    const result = cleanClassroomQaResultForClient({
      qa: { available: true, studentAnswer: "安全回答" },
      voice: { status }
    });
    assert.equal(result.voice.status, null);
  }

  for (const audioUrl of ["/generated/a.mp3", "http://example.com/a.mp3", "https://example.com/a.mp3"]) {
    const result = cleanClassroomQaResultForClient({
      qa: { available: true, studentAnswer: "安全回答" },
      voice: { audioUrl }
    });
    assert.equal(result.voice.audioUrl, audioUrl);
  }
  for (const audioUrl of [
    "//evil.example/a.mp3",
    "javascript:alert(1)",
    "data:audio/mp3;base64,AAAA",
    "file:///secret.mp3",
    "generated/a.mp3"
  ]) {
    const result = cleanClassroomQaResultForClient({
      qa: { available: true, studentAnswer: "安全回答" },
      voice: { audioUrl }
    });
    assert.equal(result.voice.audioUrl, null);
  }
});

test("QA routes use server-confirmed actor context and response cleaners", () => {
  const source = readFileSync(new URL("./server.js", import.meta.url), "utf8");
  const qaRoute = source.slice(
    source.indexOf('app.post("/api/ai/qa"'),
    source.indexOf('app.post("/api/ai/vocabulary"')
  );
  const classroomRoute = source.slice(
    source.indexOf('app.post("/api/classroom/voice-qa"'),
    source.indexOf('app.post("/api/classroom/reading"')
  );

  assert.match(qaRoute, /buildQaActorContext\(session, input,/);
  assert.match(qaRoute, /answerStudentQuestionService\(config, \{ \.\.\.input, \.\.\.actorContext \}, options\)/);
  assert.match(qaRoute, /cleanQaResultForClient\(result\)/);
  assert.match(classroomRoute, /assertClassroomStudentScope\(\{ session: req\.session \}, res, input\.studentId\)/);
  assert.doesNotMatch(classroomRoute, /prisma\.student\.findFirst/);
  assert.match(classroomRoute, /text: qa\.studentAnswer \|\| qa\.answer/);
  assert.match(classroomRoute, /cleanClassroomQaResultForClient/);
  const qaServiceIndex = classroomRoute.indexOf("const qa = await answerStudentQuestionService");
  const speechIndex = classroomRoute.indexOf("const speech = await createMiniMaxSpeechTask");
  assert.equal(qaServiceIndex >= 0 && speechIndex > qaServiceIndex, true);
});
