import assert from "node:assert/strict";
import test from "node:test";
import { answerStudentQuestionService } from "./index.js";
import { buildQaLearningRecord, sanitizeQaText } from "./qa-learning-record.js";

const validLearningSignal = {
  knowledgePoints: ["小数意义"],
  questionIntent: "concept",
  difficultySignal: "possible",
  misconceptionHypotheses: ["可能混淆十分位和十位"],
  followUpNeeded: true,
  confidence: "medium",
  safetyStatus: "pass",
  profileEligibility: true,
  blockedReason: null
};
const unavailableAnswer = "AI 问答暂时不可用，请稍后再试。";
const blockedAnswer = "这个问题暂时不能直接回答，请换一种安全、清楚的方式提问。";
const terraSolInternalForms = ["Terra", "Sol"].flatMap((identifier) => [
  `Generated by ${identifier}.`,
  `Powered by ${identifier}.`,
  `Response from ${identifier}.`,
  `Routed through ${identifier}.`,
  `provider: ${identifier}`,
  `providerId: ${identifier}`,
  `model=${identifier}`,
  `route: ${identifier}`,
  `runtime=${identifier}`,
  `${identifier} provider`,
  `${identifier} model`,
  `${identifier} route`,
  `${identifier} runtime`,
  `${identifier} provider timeout`,
  `${identifier} runtime unavailable`
]);
const lowercaseMinimaxInternalForms = [
  "response from minimax",
  "routed through minimax",
  "minimax unavailable",
  "timeout from minimax"
];
const knownStructuredKeys = [
  "content",
  "answer",
  "studentAnswer",
  "provider",
  "providerId",
  "model",
  "raw",
  "prompt",
  "debug",
  "learningSignal",
  "profileEligibility",
  "blockedReason",
  "structureValid",
  "modelRun",
  "metadata"
];
const structuredQaFragments = [
  ...knownStructuredKeys.map((key) => `{"${key}":"secret"`),
  `{"studentAnswer":"${"A".repeat(5000)}"}`,
  `prefix {"content":"${"B".repeat(5000)}"}`
];
const genericJsonFragments = [
  `{"unknown":"secret"`,
  `prefix {"custom":42`,
  `{"unknown":"${"A".repeat(5000)}"}`,
  `["secret"`,
  `["${"B".repeat(5000)}"]`,
  `prefix [{"custom":"secret"`,
  `prefix [["secret"`
];

function buildInput(overrides = {}) {
  return {
    actorRole: "student",
    identityConfirmed: true,
    ...overrides
  };
}

function buildResult(overrides = {}) {
  return {
    available: true,
    mode: "KNOWLEDGE_EXPLANATION",
    structureValid: true,
    learningSignal: validLearningSignal,
    ...overrides
  };
}

test("buildQaLearningRecord applies the learner eligibility matrix", () => {
  const cases = [
    ["student", true, true, true, "pass", true],
    ["classroom", true, true, true, "pass", true],
    ["teacher", true, true, true, "pass", false],
    ["student", false, true, true, "pass", false],
    ["classroom", false, true, true, "pass", false],
    ["student", true, false, true, "pass", false],
    ["student", true, true, false, "pass", false],
    ["student", true, true, true, "blocked", false]
  ];

  for (const [actorRole, identityConfirmed, available, structureValid, safetyStatus, eligible] of cases) {
    const record = buildQaLearningRecord(
      buildInput({ actorRole, identityConfirmed }),
      buildResult({
        available,
        structureValid,
        learningSignal: { ...validLearningSignal, safetyStatus }
      })
    );
    assert.equal(record.profileEligibility, eligible, `${actorRole}/${identityConfirmed}/${available}/${structureValid}/${safetyStatus}`);
  }
});

test("buildQaLearningRecord uses deterministic blocked reason precedence", () => {
  const cases = [
    [buildInput({ actorRole: "teacher", identityConfirmed: false }), buildResult({ available: false, structureValid: false, learningSignal: { ...validLearningSignal, safetyStatus: "blocked" } }), "teacher-test"],
    [buildInput({ identityConfirmed: false }), buildResult({ available: false, structureValid: false, learningSignal: { ...validLearningSignal, safetyStatus: "blocked" } }), "identity-unconfirmed"],
    [buildInput(), buildResult({ available: false, structureValid: false, learningSignal: { ...validLearningSignal, safetyStatus: "blocked" } }), "model-unavailable"],
    [buildInput(), buildResult({ structureValid: false, learningSignal: { ...validLearningSignal, safetyStatus: "blocked" } }), "unsafe-content"],
    [buildInput(), buildResult({ structureValid: false, learningSignal: null }), "malformed-output"]
  ];

  for (const [input, result, blockedReason] of cases) {
    assert.equal(buildQaLearningRecord(input, result).blockedReason, blockedReason);
  }
});

test("buildQaLearningRecord returns exact metadata and ignores external eligibility", () => {
  const record = buildQaLearningRecord(
    buildInput({ profileEligibility: false }),
    buildResult({
      profileEligibility: false,
      providerId: "secret-provider",
      model: "secret-model",
      raw: "secret-raw",
      learningSignal: {
        ...validLearningSignal,
        profileEligibility: false,
        provider: "secret-provider",
        model: "secret-model",
        raw: "secret-raw",
        prompt: "secret-prompt",
        debug: { trace: true },
        unknown: "secret-unknown"
      }
    })
  );

  assert.deepEqual(Object.keys(record), [
    "actorRole",
    "identityConfirmed",
    "available",
    "mode",
    "learningSignal",
    "profileEligibility",
    "blockedReason",
    "schemaVersion"
  ]);
  assert.deepEqual(Object.keys(record.learningSignal), [
    "knowledgePoints",
    "questionIntent",
    "difficultySignal",
    "misconceptionHypotheses",
    "followUpNeeded",
    "confidence",
    "safetyStatus"
  ]);
  assert.equal(record.profileEligibility, true);
  assert.equal(record.schemaVersion, "qa-learning-signal-v1");
  assert.equal(JSON.stringify(record).includes("secret"), false);
});

test("buildQaLearningRecord is conservative for untrusted roles and booleans", () => {
  const record = buildQaLearningRecord(
    buildInput({ actorRole: "student-admin", identityConfirmed: 1 }),
    buildResult({ available: 1, structureValid: 1, mode: "UNTRUSTED_MODE" })
  );

  assert.equal(record.actorRole, "unknown");
  assert.equal(record.identityConfirmed, false);
  assert.equal(record.available, false);
  assert.equal(record.mode, "KNOWLEDGE_EXPLANATION");
  assert.equal(record.profileEligibility, false);
});

test("buildQaLearningRecord rejects a missing learning signal even when structureValid is claimed", () => {
  const record = buildQaLearningRecord(buildInput(), buildResult({
    structureValid: true,
    learningSignal: null
  }));

  assert.equal(record.profileEligibility, false);
  assert.equal(record.blockedReason, "malformed-output");
  assert.equal(record.learningSignal, null);
});

test("buildQaLearningRecord rejects inherited and non-plain learning signals", () => {
  const inheritedSignal = Object.create(validLearningSignal);
  const nullPrototypeSignal = Object.assign(Object.create(null), validLearningSignal);

  for (const learningSignal of [inheritedSignal, new Map(Object.entries(validLearningSignal))]) {
    const record = buildQaLearningRecord(buildInput(), buildResult({ learningSignal }));
    assert.equal(record.profileEligibility, false);
    assert.equal(record.blockedReason, "malformed-output");
    assert.equal(record.learningSignal, null);
  }

  assert.equal(
    buildQaLearningRecord(buildInput(), buildResult({ learningSignal: nullPrototypeSignal })).profileEligibility,
    true
  );
});

test("buildQaLearningRecord treats invalid safety enums as malformed, not explicitly blocked", () => {
  const record = buildQaLearningRecord(buildInput(), buildResult({
    learningSignal: { ...validLearningSignal, safetyStatus: "unknown" }
  }));

  assert.equal(record.profileEligibility, false);
  assert.equal(record.blockedReason, "malformed-output");
  assert.equal(record.learningSignal.safetyStatus, "blocked");
});

test("buildQaLearningRecord caps signal arrays by well-formed code points and marks oversized input invalid", () => {
  const record = buildQaLearningRecord(buildInput(), buildResult({
    learningSignal: {
      ...validLearningSignal,
      knowledgePoints: Array.from({ length: 10 }, (_, index) => `${"😀".repeat(99)}${index}\uD800`),
      misconceptionHypotheses: Array.from({ length: 7 }, (_, index) => `${"乙".repeat(199)}${index}\uD800`)
    }
  }));

  assert.equal(record.profileEligibility, false);
  assert.equal(record.blockedReason, "malformed-output");
  assert.equal(record.learningSignal.knowledgePoints.length, 8);
  assert.equal(record.learningSignal.knowledgePoints.every((item) => Array.from(item).length <= 80), true);
  assert.equal(record.learningSignal.misconceptionHypotheses.length, 5);
  assert.equal(record.learningSignal.misconceptionHypotheses.every((item) => Array.from(item).length <= 160), true);
  assert.equal(JSON.stringify(record.learningSignal).includes("\uD800"), false);
});

test("buildQaLearningRecord bounds sparse signal array access before iteration", () => {
  const target = Array.from({ length: 8 }, (_, index) => `知识点${index}`);
  target.length = 1_000_000;
  const accessedIndexes = new Set();
  const knowledgePoints = new Proxy(target, {
    get(array, property, receiver) {
      if (/^(?:0|[1-9]\d*)$/.test(String(property))) {
        const index = Number(property);
        if (index >= 8) throw new Error(`unbounded indexed read: ${index}`);
        accessedIndexes.add(index);
      }
      return Reflect.get(array, property, receiver);
    },
    getOwnPropertyDescriptor(array, property) {
      if (/^(?:0|[1-9]\d*)$/.test(String(property))) {
        const index = Number(property);
        if (index >= 8) throw new Error(`unbounded own-property check: ${index}`);
        accessedIndexes.add(index);
      }
      return Reflect.getOwnPropertyDescriptor(array, property);
    }
  });

  const record = buildQaLearningRecord(buildInput(), buildResult({
    learningSignal: { ...validLearningSignal, knowledgePoints }
  }));

  assert.equal(record.profileEligibility, false);
  assert.equal(record.blockedReason, "malformed-output");
  assert.deepEqual(record.learningSignal.knowledgePoints, Array.from({ length: 8 }, (_, index) => `知识点${index}`));
  assert.deepEqual([...accessedIndexes], [0, 1, 2, 3, 4, 5, 6, 7]);
});

test("buildQaLearningRecord marks every altered signal item invalid", () => {
  const cases = [
    ["知识\u0000点", "知识 点"],
    [" 知识点 ", "知识点"],
    ["知识\uD800点", "知识�点"]
  ];

  for (const [source, expected] of cases) {
    const record = buildQaLearningRecord(buildInput(), buildResult({
      learningSignal: { ...validLearningSignal, knowledgePoints: [source] }
    }));
    assert.equal(record.profileEligibility, false);
    assert.equal(record.blockedReason, "malformed-output");
    assert.deepEqual(record.learningSignal.knowledgePoints, [expected]);
  }
});

test("buildQaLearningRecord bounds normalization work for hostile signal items", { concurrency: false }, () => {
  const descriptor = Object.getOwnPropertyDescriptor(String.prototype, "toWellFormed");
  const original = descriptor.value;
  let largestNormalizedInput = 0;
  Object.defineProperty(String.prototype, "toWellFormed", {
    ...descriptor,
    value() {
      const source = this.valueOf();
      largestNormalizedInput = Math.max(largestNormalizedInput, source.length);
      return original.call(source);
    }
  });

  try {
    const record = buildQaLearningRecord(buildInput(), buildResult({
      learningSignal: {
        ...validLearningSignal,
        knowledgePoints: ["知".repeat(1_000_000)]
      }
    }));
    assert.equal(record.profileEligibility, false);
    assert.equal(Array.from(record.learningSignal.knowledgePoints[0]).length, 80);
    assert.equal(largestNormalizedInput <= 80 * 2 + 128, true);
  } finally {
    Object.defineProperty(String.prototype, "toWellFormed", descriptor);
  }
});

test("buildQaLearningRecord drops internal labels and embedded JSON from signal text", () => {
  const record = buildQaLearningRecord(buildInput(), buildResult({
    learningSignal: {
      ...validLearningSignal,
      knowledgePoints: [
        "小数意义",
        "provider: secret-provider",
        "model=gpt-secret",
        "前缀 {\"raw\":\"secret-raw\"} 后缀",
        "Generated by GPT-5.6",
        "Response from the Terra model",
        "Routed through the Sol provider"
      ],
      misconceptionHypotheses: [
        "继续观察",
        "prompt: secret-prompt",
        "debug=secret-debug",
        "OpenAI generated this",
        "DeepSeek response",
        "Powered by MiniMax"
      ]
    }
  }));

  assert.deepEqual(record.learningSignal.knowledgePoints, ["小数意义"]);
  assert.deepEqual(record.learningSignal.misconceptionHypotheses, ["继续观察"]);
  assert.equal(record.profileEligibility, false);
  assert.equal(record.blockedReason, "malformed-output");
  assert.equal(JSON.stringify(record).includes("secret"), false);
});

test("answerStudentQuestionService never persists oversized runner signals as eligible", async () => {
  let qaSessionData = null;
  const qaRunner = async () => ({
    ...buildResult({
      learningSignal: {
        ...validLearningSignal,
        knowledgePoints: Array.from({ length: 10 }, () => "知".repeat(100)),
        misconceptionHypotheses: Array.from({ length: 7 }, () => "误".repeat(200))
      }
    }),
    studentAnswer: "安全回答",
    answer: "安全回答",
    modelRun: null
  });
  const prisma = {
    qaSession: {
      create: async ({ data }) => {
        qaSessionData = data;
        return { id: "qa1" };
      }
    }
  };

  await answerStudentQuestionService({}, buildInput({ question: "问题" }), { qaRunner, prisma });

  assert.equal(qaSessionData.metadata.profileEligibility, false);
  assert.equal(qaSessionData.metadata.learningSignal.knowledgePoints.length, 8);
  assert.equal(qaSessionData.metadata.learningSignal.knowledgePoints.every((item) => Array.from(item).length <= 80), true);
  assert.equal(qaSessionData.metadata.learningSignal.misconceptionHypotheses.length, 5);
  assert.equal(qaSessionData.metadata.learningSignal.misconceptionHypotheses.every((item) => Array.from(item).length <= 160), true);
});

test("answerStudentQuestionService persists only approved QA metadata", async () => {
  const writes = { modelRuns: [], qaSessions: [], voiceInteractions: [] };
  const qaRunner = async () => ({
    ...buildResult(),
    studentAnswer: "安全回答",
    answer: "兼容回答",
    providerId: "secret-provider",
    modelRun: { provider: "secret-provider", model: "secret-model", status: "SUCCESS" }
  });
  const prisma = {
    modelRun: { create: async ({ data }) => (writes.modelRuns.push(data), { id: "mr1" }) },
    qaSession: { create: async ({ data }) => (writes.qaSessions.push(data), { id: "qa1" }) },
    voiceInteraction: { create: async ({ data }) => (writes.voiceInteractions.push(data), { id: "voice1" }) }
  };

  const result = await answerStudentQuestionService({}, {
    actorRole: "classroom",
    identityConfirmed: true,
    studentId: "s1",
    deviceId: "d1",
    subject: "数学",
    question: "0.5 是什么？"
  }, { qaRunner, prisma });

  assert.equal(writes.qaSessions[0].answer, "安全回答");
  assert.deepEqual(writes.qaSessions[0].metadata, buildQaLearningRecord(
    buildInput({ actorRole: "classroom" }),
    await qaRunner()
  ));
  assert.equal(writes.voiceInteractions[0].answerSummary, "安全回答");
  assert.deepEqual(writes.voiceInteractions[0].metadata, {
    qaSessionId: "qa1",
    available: true,
    mode: "KNOWLEDGE_EXPLANATION"
  });
  assert.deepEqual(result.persisted, {
    modelRunId: "mr1",
    qaSessionId: "qa1",
    voiceInteractionId: "voice1"
  });
});

test("answerStudentQuestionService uses the safe legacy answer and honors persist false", async () => {
  const qaRunner = async () => ({
    ...buildResult(),
    studentAnswer: "",
    answer: "兼容安全回答",
    modelRun: { provider: "test", model: "test", status: "SUCCESS" }
  });
  const prisma = new Proxy({}, {
    get() {
      throw new Error("persistence must not be touched");
    }
  });

  const result = await answerStudentQuestionService({}, buildInput({ question: "问题" }), {
    qaRunner,
    persist: false,
    prisma
  });

  assert.equal(result.answer, "兼容安全回答");
  assert.deepEqual(result.persisted, {
    modelRunId: null,
    qaSessionId: null,
    voiceInteractionId: null
  });
});

test("answerStudentQuestionService canonicalizes malicious runner answers before persistence and return", async () => {
  const cases = [
    '{"content":"safe","provider":"secret-provider","raw":"secret-raw"}',
    '回答前缀 {"content":"safe","provider":"secret-provider"} 回答后缀',
    { raw: "secret-object" },
    "Generated by GPT-5.6.",
    "OpenAI generated this answer.",
    "DeepSeek response unavailable.",
    "Powered by MiniMax.",
    "providerId: gpt56",
    "gpt56",
    ...terraSolInternalForms,
    ...lowercaseMinimaxInternalForms,
    ...structuredQaFragments,
    ...genericJsonFragments
  ];

  for (const studentAnswer of cases) {
    const writes = { qaSession: null, voiceInteraction: null };
    const qaRunner = async () => ({
      ...buildResult(),
      studentAnswer,
      answer: "不应回退的兼容回答",
      modelRun: null
    });
    const prisma = {
      qaSession: {
        create: async ({ data }) => {
          writes.qaSession = data;
          return { id: "qa1" };
        }
      },
      voiceInteraction: {
        create: async ({ data }) => {
          writes.voiceInteraction = data;
          return { id: "voice1" };
        }
      }
    };

    const result = await answerStudentQuestionService({}, {
      ...buildInput({ question: "问题" }),
      deviceId: "d1"
    }, { qaRunner, prisma });

    assert.equal(writes.qaSession.answer, unavailableAnswer);
    assert.equal(writes.qaSession.metadata.available, false);
    assert.equal(writes.qaSession.metadata.profileEligibility, false);
    assert.equal(writes.voiceInteraction.answerSummary, unavailableAnswer);
    assert.equal(writes.voiceInteraction.metadata.available, false);
    assert.equal(result.studentAnswer, unavailableAnswer);
    assert.equal(result.answer, unavailableAnswer);
    assert.equal(result.available, false);
    assert.equal(JSON.stringify({ writes, result }).includes("secret"), false);
    assert.equal(JSON.stringify({ writes, result }).includes("不应回退"), false);
  }
});

test("answerStudentQuestionService preserves plain and blocked canonical answers", async () => {
  const cases = [
    ["正常回答", validLearningSignal, true],
    ["A model helps us explain a math pattern.", validLearningSignal, true],
    ["The words deep seek are separate ordinary words.", validLearningSignal, true],
    ["The minimax algorithm explores game trees.", validLearningSignal, true],
    ["The minimax algorithm generated the best move.", validLearningSignal, true],
    ["Terra generated a map for the geography lesson.", validLearningSignal, true],
    ["Sol generated heat in the story about the Sun.", validLearningSignal, true],
    ["Sol is the Latin name for the Sun; terra means earth.", validLearningSignal, true],
    ["The set is {1, 2, 3}.", validLearningSignal, true],
    ["Use [a, b] as a bracketed example.", validLearningSignal, true],
    ["The interval is [0, 1).", validLearningSignal, true],
    ["Compare the intervals (a, b] and [c, d).", validLearningSignal, true],
    ['The word "content" appears in quoted prose.', validLearningSignal, true],
    [blockedAnswer, { ...validLearningSignal, safetyStatus: "blocked" }, true]
  ];

  for (const [studentAnswer, learningSignal, available] of cases) {
    const qaRunner = async () => ({
      ...buildResult({ learningSignal }),
      studentAnswer,
      answer: studentAnswer,
      modelRun: null
    });
    const result = await answerStudentQuestionService({}, buildInput({ question: "问题" }), {
      qaRunner,
      persist: false
    });
    assert.equal(result.studentAnswer, studentAnswer);
    assert.equal(result.answer, studentAnswer);
    assert.equal(result.available, available);
  }
});

test("answerStudentQuestionService caps canonical answers by well-formed code points", async () => {
  const qaRunner = async () => ({
    ...buildResult(),
    studentAnswer: `答\uD800${"😀".repeat(2100)}`,
    answer: "不应使用",
    modelRun: null
  });
  const result = await answerStudentQuestionService({}, buildInput({ question: "问题" }), {
    qaRunner,
    persist: false
  });

  assert.equal(Array.from(result.studentAnswer).length, 2000);
  assert.equal(result.studentAnswer.includes("\uD800"), false);
  assert.equal(result.answer, result.studentAnswer);
  assert.equal(result.available, true);
});

test("sanitizeQaText bounds normalization work before processing hostile input", { concurrency: false }, () => {
  const descriptor = Object.getOwnPropertyDescriptor(String.prototype, "toWellFormed");
  const original = descriptor.value;
  let largestNormalizedInput = 0;
  Object.defineProperty(String.prototype, "toWellFormed", {
    ...descriptor,
    value() {
      const source = this.valueOf();
      largestNormalizedInput = Math.max(largestNormalizedInput, source.length);
      return original.call(source);
    }
  });

  try {
    const maxLength = 80;
    const hugeSuffix = "😀".repeat(600_000);
    const visible = sanitizeQaText(hugeSuffix, { maxLength });
    assert.equal(Array.from(visible).length, maxLength);
    assert.equal(visible, "😀".repeat(maxLength));

    const blocked = sanitizeQaText(`前缀 providerId: gpt56 ${hugeSuffix}`, { maxLength });
    assert.equal(blocked, "");
    assert.equal(largestNormalizedInput <= maxLength * 2 + 128, true);
  } finally {
    Object.defineProperty(String.prototype, "toWellFormed", descriptor);
  }
});
